my_string=input('Введите текст: ')
print('В тексте',len(my_string.replace(' ','')),'символов.')
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[:1])
print(my_string[::-1][:1])